import { PlusIcon, TrashIcon } from "@heroicons/react/24/solid";
import dayjs from "dayjs";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useForm } from "react-hook-form";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const { data, isLoading } = trpc.useQuery(["todos.getAll"]);
  const { handleSubmit, register } = useForm();
  return (
    <>
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          padding: "28px 0",
        }}
      >
        <h1 style={{ textAlign: "center", margin: 0 }}>Todos list app</h1>
      </div>
      <div
        style={{
          display: "flex",
          padding: "0 36px",
        }}
      >
        <div
          style={{
            flexGrow: 1,
            borderRight: "1px solid grey",
            position: "relative",
          }}
        >
          <div style={{ position: "sticky", top: 20, paddingRight: 12 }}>
            <h2>Create Todo</h2>
            <form
              onSubmit={handleSubmit((val) => {
                console.log(val);
              })}
            >
              <div style={{ display: "flex", flexDirection: "column" }}>
                <label htmlFor="title">
                  <span>Title</span>
                </label>
                <input type="text" {...register("title")} />
              </div>
              <button type="submit">Create</button>
            </form>
          </div>
        </div>
        <div
          style={{
            flexGrow: 2,
            padding: "0 24px",
          }}
        >
          <div
            style={{
              display: "flex",
              flexDirection: "column",
            }}
          >
            {isLoading && <div>Loading...</div>}
            {!isLoading && data && (
              <>
                <div>
                  {data.length === 0 && <h2>No todos yet! Create one</h2>}
                  {data.map((todo) => {
                    return (
                      <Link key={todo.id} href={`/todo/${todo.id}`}>
                        <a>
                          <div
                            style={{
                              marginBottom: 16,
                              border: "1px solid grey",
                              padding: 16,
                              borderRadius: 6,
                              position: "relative",
                              paddingRight: 66,
                            }}
                          >
                            <h3
                              style={{
                                margin: 0,
                                fontWeight: 500,
                                maxWidth: "30ch",
                                overflow: "hidden",
                                textOverflow: "ellipsis",
                                whiteSpace: "nowrap",
                              }}
                            >
                              {todo.title}
                            </h3>
                            <small>
                              Criado:{" "}
                              {dayjs(todo.createdAt).format("DD/MM HH:mm")}
                            </small>
                            <div
                              style={{
                                position: "absolute",
                                right: 8,
                                top: 0,
                                bottom: 0,
                                color: "red",
                                alignItems: "center",
                                display: "flex",
                              }}
                            >
                              <TrashIcon
                                style={{
                                  height: 46,
                                  width: 46,
                                  padding: 6,
                                  border: "2px solid red",
                                  borderRadius: 6,
                                  cursor: "pointer",
                                }}
                              />
                            </div>
                          </div>
                        </a>
                      </Link>
                    );
                  })}
                </div>
              </>
            )}
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;
